### ISSUE TITLE
Sort assets in asset selector

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hydration-ui#1431]
<img width="500" alt="Screenshot 2024-06-21 at 16 42 17" src="https://github.com/galacticcouncil/HydraDX-ui/assets/3409250/9c9df1e1-f797-4a72-9d68-c2bb3c3fe657">

Sort by (all of these rules should apply at the same time)

0. Selected asset
1. All by $ value held rest if 0$
2. HDX
3. DOT
4. USDC
5. USDT
6. iBTC
7. vDOT
8. wETH
9. wBTC
10. other sufficient by ticker ascending
11. external by ticker ascending

**Comment by vkulinich-cl** [comment]
Done
