### ISSUE TITLE
Remove "admin rights revoked" warning for KOL, update logo

### ISSUE THREAD

**Issue by kolkadot** [galacticcouncil/hydration-ui#1482]
Ticker: KOL
Name: Kolkadot
Asset Hub ID: 86
HydraDX ID: 1000199
Total Supply: 86'586'711 

**Admin right revocation**

- [x] Team roles set to treasury address: https://assethub-polkadot.subscan.io/extrinsic/6635974-2
- [x] Ownership transferred to treasury address: https://assethub-polkadot.subscan.io/extrinsic/6635975-2

Could you pls also update the logo?

![kolkadot](https://github.com/galacticcouncil/hydration-ui/assets/174952226/5a3975c6-744d-4d97-ac0b-5f138f9a0357)

**Comment by jak-pan** [comment]
Fixed with https://github.com/galacticcouncil/intergalactic-asset-metadata/pull/5
