### ISSUE TITLE
XYK Farms info not displayed correctly after farm setup

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/hydration-ui#1484]
**Setting up farms example:**

Global farm:
```0x5f0000008a5d784563010000000000000000d00c140001000000a3420f00a3420f00e27d987db9ed2a7a48f4137c997d610226dc93bf256c9026268b0b8489bb9862fcb99cc50100000000e87648170000000000000000000000403f18fa51cc431f0600000000000000```

Yield farm:
```0x5f030400000005000000a3420f00000064a7b3b6e00d0000000000000000010000b2d3595bf0060000000000000000e02e0000```

**Outcome:**
![image](https://github.com/galacticcouncil/hydration-ui/assets/75261756/c6128e13-8b41-432d-bdf4-85ba1e7b6297)

**Comment by green-jay** [comment]
@jak-pan @DuriSK imo this should be high prio as we have at least 1 partner ready to start farms on xyk pools

**Comment by jak-pan** [comment]
> @jak-pan @DuriSK imo this should be high prio as we have at least 1 partner ready to start farms on xyk pools

This only happens if there is nobody in farm AFAIK
