### ISSUE TITLE
Add custom transaction submission screen

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hydration-ui#1487]
One textarea input field and submit button for encodedCallData similar to https://polkadot.js.org/apps/#/extrinsics/decode (we don't need to decode it as it's done in tx confirm window).

This screen should be accessible only by link and feature warning on top.

`Warning! Do not submit transactions somebody sent you in a message. Always check what you are sending on transaction confirmation screen or in https://polkadot.js.org/apps/#/extrinsics/decode`

(wen [feature in tx conf screen? ](https://github.com/galacticcouncil/hydration-ui/issues/1430) ?)

**Comment by vkulinich-cl** [comment]
Shiped
