### ISSUE TITLE
Add msg that DOT is not available to xcm to Assethub 

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1545]
There were severals members that seems confused why not appear DOT on the options, so they didn't know that need to xcm to Polkadot and then to Assethub 

Put a msg explaining that
![Screenshot_20240729_130543_Chrome](https://github.com/user-attachments/assets/8ef49180-687c-482b-99a1-33c0811ed5e0)

**Comment by jak-pan** [comment]
The DOT transfer is being fixed ATM keep tight.
