### ISSUE TITLE
Remove "admin rights revoked" warning for BEEFY

### ISSUE THREAD

**Issue by polkadotbeefy** [galacticcouncil/hydration-ui#1550]
Ticker: BEEFY
Name: BEEFY
Asset Hub ID: 420
HydraDX ID: 1000036
Total Supply: 13’110’000’000’000’000
Decimals: 2

**Admin right revocation**

- ✅ Team roles set to treasury address: https://assethub-polkadot.subscan.io/extrinsic/6807990-2
- ✅ Ownership transferred to treasury address: https://assethub-polkadot.subscan.io/extrinsic/6808005-2

**Comment by jak-pan** [comment]
This is automatic when you transfer the roles to treasury address.
