### ISSUE TITLE
On the xcm from Hydration to Moonbeam  evm appear the wrong asset like fees

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1561]
Says the source chain fees is PINK

![Screenshot_20240807_070740_Nova](https://github.com/user-attachments/assets/49bf85de-54be-4d9f-8abc-5dcde7551778)
![Screenshot_20240807_070731_Nova](https://github.com/user-attachments/assets/871bbce0-4d6d-4707-9dd3-f43b48f2fc45)

**Comment by DuriSK** [comment]
Fixed
