### ISSUE TITLE
ADD AJUNA LOGO TO CROSSCHAIN UI

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/hydration-ui#1670]
<img width="601" alt="image" src="https://github.com/user-attachments/assets/cbd30f5c-1a4c-48cf-9f9a-e8be3bd0b49e">

**Comment by DuriSK** [comment]
Network:
Ajuna_colorful_landscape_logo_svg.
Asset:
Ajuna_colorful_icon_logo_svg.svg
