### ISSUE TITLE
Proxied account can't be viewed as a wallet

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/hydration-ui#1678]
e.g. account `7LcF8b5GSvajXkSChhoMFcGDxF9Yn9unRDceZj1Q6NYox8HY`
UI suggests you should view it but doesn't let you click the button

![image](https://github.com/user-attachments/assets/1e53c6ac-2484-4568-86ef-a7dc1b5849ca)

**Comment by jak-pan** [comment]
We might want to redesign this a little bit. It got "broken" when we introduced new wallet flow. But even before it work in a weird way that seemed buggy. (Unless you have the proxy when it works normally)

**Comment by jak-pan** [comment]
Till this is fixed properly the link method still works i.e. https://app.hydration.net/liquidity/all-pools?account=7LcF8b5GSvajXkSChhoMFcGDxF9Yn9unRDceZj1Q6NYox8HY
