### ISSUE TITLE
Unable to unlock tokens

### ISSUE THREAD

**Issue by josepot** [galacticcouncil/hydration-ui#1682]
👋 there!

When an account has removed their votes, but hasn't yet called the `democracy.unlock` extrinsic this is what the UI displays:

![image](https://github.com/user-attachments/assets/716daea6-4cb4-49be-ad10-7b9809d4799d)

Also, going into the PJS console doesn't help in this situation. The user has to manually create the `Democracy.unlock` extrinsic from a developer console. This is what happened with the [following account](https://hydration.subscan.io/account/7N8QAiy7s7KVJnKE95E4dZED943XEYJDNtHcwxXtkTXfPq6W).

I'm guessing that it's a state a bit difficult to detect, but IMO the UI should account for this state-permutation. Otherwise, it seems that the funds are permanently locked 🙂.

Leaving this aside, I want to congratulate you for the amazing UI that you got here 🙌.

**Comment by jak-pan** [comment]
cc @jvonasek
