### ISSUE TITLE
wrong LP fees

### ISSUE THREAD

**Issue by lolmcshizz** [galacticcouncil/hydration-ui#1734]
these are wrong
![image](https://github.com/user-attachments/assets/e45f3c92-1dea-4012-9a84-2811a7a567e4)
that's the LP fee on each trade, not the fees from LP fee
here you can see fee from LP fee
![image](https://github.com/user-attachments/assets/57f8fb1b-c98f-47d0-969c-80e51ca147aa)
this appears to be showing the LP fee instead of fee from LP fee
![image](https://github.com/user-attachments/assets/70ccb70d-e8d5-45cd-8cfd-ad03f8021b7b)

**Comment by green-jay** [comment]
Good catch, was about to create an issue, LP fee != APR. Also when farm ends (all farm rewards 0%) it should revert to non-farm view? or consolidate the rest of non-yield assets
