### ISSUE TITLE
UI problem on the cross-chain tab, sending USDC from Hydration to Moonbeam 

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1754]
In asset to receive, in the case of usdc, 0 appears, regardless of the amount placed above

This does not happen with other assets (or at least with glrm, hdx and dot) the others were not available so I could not test them
![Screenshot_20241023_165212_Nova](https://github.com/user-attachments/assets/3b50adeb-1a35-447b-9a66-471c92666457)
![Screenshot_20241023_165200_Nova](https://github.com/user-attachments/assets/f3a608f2-6eec-49e8-b9f5-2be59adf9b6b)
![Screenshot_20241023_165152_Nova](https://github.com/user-attachments/assets/9f1d1845-f3a3-4d75-b76c-2d3d7b92b4a7)

**Comment by nohaapav** [comment]
@joseJRJR fixed on mainet
