### ISSUE TITLE
Not appear the rewards from the farm myth/dot on the UI

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1784]
Not appear nothing, but if you withdraw the LP, you get the rewards so is something visual 

![Screenshot_20241102_112106_Chrome](https://github.com/user-attachments/assets/c8ca443f-0390-472c-b38c-eedb0625c46b)
![Screenshot_20241102_111920_Chrome](https://github.com/user-attachments/assets/036f1bc4-2f93-45fe-afa8-5f9db8b49651)

**Comment by vkulinich-cl** [comment]
@joseJRJR hey, could you check it out again? Rewards are displayed for that wallet. And which LP was withdrawed, user exited the farm position?
