### ISSUE TITLE
Volumen is not changing on liquidity tab

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1788]
Some users are reporting that is showing the same amount like 4 days ago, and at least for now i can confirm that haven't changed on some hours

![Screenshot_20241103_162347_Chrome](https://github.com/user-attachments/assets/5cfee028-d7be-49ad-9d8c-be4063cf59e1)
![Screenshot_20241103_162558_Chrome](https://github.com/user-attachments/assets/758fd42b-9d93-4324-b421-1691b6bd0d75)

**Comment by joseJRJR** [comment]
@vkulinich-cl this is fixed? I still see the same numbers for the volume of each asset 
![Screenshot_20241104_115335_Nova](https://github.com/user-attachments/assets/a8d25dd0-2714-4d53-abd6-2098edca843e)

**Comment by vkulinich-cl** [comment]
> @vkulinich-cl this is fixed? I still see the same numbers for the volume of each asset ![Screenshot_20241104_115335_Nova](https://private-user-images.githubusercontent.com/123791232/382824846-a8d25dd0-2714-4d53-abd6-2098edca843e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NDc0MzgsIm5iZiI6MTczMDc0NzEzOCwicGF0aCI6Ii8xMjM3OTEyMzIvMzgyODI0ODQ2LWE4ZDI1ZGQwLTI3MTQtNGQ1My1hYmQ2LTIwOThlZGNhODQzZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxOTA1MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzQ1MjQ4YTgxMDEwY2U5NGRiMjdiNmNhYmI5Y2U2NDk4N2YyODI2MmYxZGI3NGJhNzFkY2ZjZDY3ZmI0YWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZL7FbOCmkG50mFV-PRDU17AwTi63hwNGltKXdsAkd1I)

yep, looks like an issue with API. Already reported it
