### ISSUE TITLE
Cross-chain don't work if have selected HDX like fees - says that dont have enough hdx for the tx

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1791]
If an user change the asset fee to any other, work without  problem

This affect all cross-chain if you use hdx like fees

![Screenshot_20241104_183628_Nova](https://github.com/user-attachments/assets/cbdf1225-64f7-4646-8b73-1c09c853adb2)
![image-51](https://github.com/user-attachments/assets/2783d5de-66e0-46d9-9201-d3bd98bf7d29)

**Comment by nohaapav** [comment]
Fixed on mainet
