### ISSUE TITLE
Wrong amount on "my liquidity " tab

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1792]
People are reporting that the "liquidity tab" is showing the wrong number on the total (this being higher than it should be)

In this example it appears that he has 5k, when in reality he only has $450 on the myth/dot pool

It seems to have affected only the isolated pools
![Screenshot_20241104_184309_Chrome](https://github.com/user-attachments/assets/f029dee3-c366-4cc7-8d23-e4048f5f4d79)
![Screenshot_20241104_184259_Chrome](https://github.com/user-attachments/assets/1d31cc9f-07c2-4446-91d4-64b919b90db5)

**Comment by vkulinich-cl** [comment]
@joseJRJR, sir, could you attach a wallet address to the gh ticket next time, please. It's much easier to debug

**Comment by joseJRJR** [comment]
@vkulinich-cl sure, can use this one

14KRE9C4bSSFtzzgQ4GkZx3A2L5LiUZEL65p2qxgLN8vLMkY

**Comment by joseJRJR** [comment]
@vkulinich-cl seems like this user, already moved the positions, so cant use to debug. Will try to look for the other one that repored

**Comment by vkulinich-cl** [comment]
> @vkulinich-cl seems like this user, already moved the positions, so cant use to debug. Will try to look for the other one that repored

it's not necessary. I already fixed that. It's just for future tickets :)

**Comment by vkulinich-cl** [comment]
but it's not released yet. The ticket is closing automatically, when a fix is merged
