### ISSUE TITLE
WalletConnect Missing or invalid. request() chainId: undefined

### ISSUE THREAD

**Issue by Tbaut** [galacticcouncil/hydration-ui#1797]
Hey hey,
when I'm trying to make a swap tx with Multix conncected to hydration, upon signing I get a 
> Missing or invalid. request() chainId: undefined

Any chance you can take a look at it?
![image](https://github.com/user-attachments/assets/05ae84b8-037e-4974-a0a8-ecda62b04b46)

**Comment by jak-pan** [comment]
What RPC do you use and is this EVM or Substrate wallet connect?

**Comment by DuriSK** [comment]
ChainId issue fixed, walletconnect is currently working on full support and performance should be better when new kit will be out
