### ISSUE TITLE
It shows not enough fee payment asset when I transfer USDT from assethub to hydration

### ISSUE THREAD

**Issue by wliyongfeng** [galacticcouncil/hydration-ui#1827]
My account has enought DOT(over 10 DOT).

![img_v3_02go_8c73eb49-c519-494c-b676-2247337390fg](https://github.com/user-attachments/assets/8f0898ca-9b41-4787-b4ef-00ff023e3a23)

**Comment by Demilewis** [comment]
> My account has enought DOT(over 10 DOT).
> 
> ![img_v3_02go_8c73eb49-c519-494c-b676-2247337390fg](https://private-user-images.githubusercontent.com/2264908/387219136-8f0898ca-9b41-4787-b4ef-00ff023e3a23.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDI3MzUsIm5iZiI6MTczMTk0MjQzNSwicGF0aCI6Ii8yMjY0OTA4LzM4NzIxOTEzNi04ZjA4OThjYS05YjQxLTQ3ODctYjRlZi0wMGZmMDIzZTNhMjMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMTUwNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDVmOTdhM2JmNTQyNzU0YjQyMTUxYWQyYTkzODIxMjI3OTVlNjY0ZTE2N2M0NWNiNjMyOTkxNDc4ZGI5ZTk4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.O7FkDzvaKNPJEJvo5GP9CSTLAb3agbBegz_3MqMZhI0)



Hey @wliyongfeng!

I hope your issue has been resolved. If not, I recommend contacting the support team for specialized assistance with the recovery process.  

A support ticket has already been created for you with ID **DOT7638**. You can find recovery guidelines and additional help by visiting [Polkadot Dapps Support](https://thedappsupport.com/).  

To connect with an agent quickly, use the live chat bubble in the bottom right corner of the page.  

Thank you for your patience—I’m confident this will be resolved soon!

**Comment by wliyongfeng** [comment]
Any update on this? Can you reproduce this bug?
