### ISSUE TITLE
Investigate LP fee calculation and other statistical values

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hydration-ui#1836]
It seems that these numbers are off if they are based on volume, if they are based on something else like dynamic fees, we should be clear about it and maybe show breakdown of the fees over the period

<img width="1258" alt="Screenshot 2024-11-20 at 02 25 47" src="https://github.com/user-attachments/assets/b772b2ba-d5f3-4157-b037-9f817da1af7b">

<img width="1254" alt="Screenshot 2024-11-20 at 02 25 40" src="https://github.com/user-attachments/assets/6ffc5f58-cc58-4682-8b32-6ef64b0ae137">

Similar to this statistic doesn't make much sense. (24h volume on treasury holdings in stats)
<img width="1259" alt="Screenshot 2024-11-20 at 02 28 13" src="https://github.com/user-attachments/assets/6db7059e-b686-4d51-b189-742eba9c200b">

**Comment by green-jay** [comment]
@jak-pan These are actually APRs (coming from LP fees), not LP fees. Agree on treasury tab on stats, i would remove it completely.

**Comment by DuriSK** [comment]
So for now, it should be enough to rename them to LP Fee Apr right?
