### ISSUE TITLE
Usdt/tokens chart

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#1855]
When people is trading with any stablecoin, dont should matter if is selling or buying the token, but should appear the price of the token compared with usdt

But when you want to sell on Hydration,  appear on the other way, wich is confusing for users

This should be always the chart  ( for now only appear when you buy x token, DOT on this case)
![Screenshot_20241123_110736_Chrome](https://github.com/user-attachments/assets/5b3cf7f3-f4ff-4067-a652-41bc413a7fb3)

And if you want to sell. Appear of this way
![Screenshot_20241123_110744_Chrome](https://github.com/user-attachments/assets/21885916-f27b-43f5-abde-2120036c6dce)

**Comment by jak-pan** [comment]
This looks like something we won't do. We will probably add some way to switch the chart though
