### ISSUE TITLE
Never show 0 balance when value is not loaded.

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hydration-ui#1886]
This is happening across the app, but the worst offender is wallet account selection window which shows 0 a lot and can cause serious heart condition in users. (Talking from personal experience)

Don't have screenshot but it usually happens when the app is running for longer in the bg and the wallet selector is opened.

**Comment by CJ13th** [comment]
@vkulinich-cl Is there any short term quick fix on the user side for this? I want to use the platform but all balances are 0, happening on both Brave and  Chrome.

**Comment by CJ13th** [comment]
@vkulinich-cl 

https://assethub-polkadot.subscan.io/account/5Dd4iGTP6TexDMaeSKi8mjdL6gjTj7gaEWwRuXxBrD27q6a3

<img width="1435" alt="Screenshot 2024-12-09 at 13 33 39" src="https://github.com/user-attachments/assets/91261cc1-ad41-470d-bd7d-df8576b71e21">
<img width="1439" alt="Screenshot 2024-12-09 at 13 34 03" src="https://github.com/user-attachments/assets/76eda0c1-aa3d-4b3e-834b-6e0a927194e8">

**Comment by vkulinich-cl** [comment]
@CJ13th hey, it hasn't been released to production yet. The issue was closed automatically. But I'll double check the issue with your wallet

**Comment by vkulinich-cl** [comment]
@CJ13th you sent a link from asset-hub, but not hydration. On hydration, that account have nothing to display

**Comment by CJ13th** [comment]
@vkulinich-cl Ahhh sorry ok, that makes sense!
