### ISSUE TITLE
Evm non compatible with NovaWalletApp 

### ISSUE THREAD

**Issue by joseJRJR** [galacticcouncil/hydration-ui#857]
I tried to cross-chain some glmr and eth using the evm account that give NovaWalletApp to us for Moonbeam and the site refreshed 

https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/6fa0f875-d756-4c67-94e9-36cd75cbdca8

https://github.com/galacticcouncil/HydraDX-ui/assets/123791232/1e6a901e-4b2a-49d5-a387-5f62d7b640b1

**Comment by jak-pan** [comment]
@DuriSK is this fixed?

**Comment by jvonasek** [comment]
Seems like issue inside Nova Wallet when using EVM provider. Refreshing happens in other dApps aswell.

**Comment by joseJRJR** [comment]
> Seems like issue inside Nova Wallet when using EVM provider. Refreshing happens in other dApps aswell.

Yes this is not an error, they refresh the site to connect and emulate the evm side, the same happen if you are using evm and now try to connect to the substrate side, can close this, at that moment not was clear
